# Generated by Django 2.2.9 on 2020-02-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_yes'),
    ]

    operations = [
        migrations.CreateModel(
            name='US',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.PositiveIntegerField()),
            ],
        ),
    ]
